arb-dir: lib/l10n
output-dir: lib/l10n/generated/i18n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: toBeLocalized.txt
synthetic-package: false