// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-oBONlzclHP2q02v-P2jreXmZgGydA9o',
    appId: '1:852585975159:web:c30fe82fdbc70a1cf5e572',
    messagingSenderId: '852585975159',
    projectId: 'surprise-xiaokeai',
    authDomain: 'surprise-xiaokeai.firebaseapp.com',
    storageBucket: 'surprise-xiaokeai.appspot.com',
    measurementId: 'G-ZHV6PHBQFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQYj2NyJPZ_ziCkBhQXzEhW26wRRBG9E',
    appId: '1:852585975159:android:ebbd31281bc2f85ff5e572',
    messagingSenderId: '852585975159',
    projectId: 'surprise-xiaokeai',
    storageBucket: 'surprise-xiaokeai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDed0qOuohMxVJu9_xUfpA-fbbsfQ5DFHw',
    appId: '1:852585975159:ios:b7546a3d7f9b1a3bf5e572',
    messagingSenderId: '852585975159',
    projectId: 'surprise-xiaokeai',
    storageBucket: 'surprise-xiaokeai.appspot.com',
    iosBundleId: 'com.lukecreated.xiaokeai',
  );
}
